name: aliddns
on:
  schedule:
    - cron:  '0 19 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: ./desk.sh
