name: aliddns
on:
  schedule:
    - cron:  '0 19 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    
steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'aliddns'
        run: bash ./desk.sh
