name: AUTO ALIDDNS
on:
  workflow_dispatch:
  schedule:
    # 北京时间24：00执行（北京时间=UCT+8）
    - cron: "0 10 * * *"

jobs:
  aliddns:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # 安装python脚本环境
    # - uses: actions/setup-python@v3
    # 安装脚本需要的环境
    # - run: pip install requests
    - run: bash desk.sh
