name: Aliddns Actions
on:
  schedule:
    - cron: "0 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
  
steps:
   uses: actions/checkout@v2
   name: Create ZIP package artifact
   name: Run aliddns
   run: bash desk.sh
